version: "3.9"
services:
  parser:
    build:
      context: ./VDPR-Parser
      dockerfile: ./Dockerfile
    ports:
      - "3000:5000"
    extra_hosts:
    - "host.docker.internal:host-gateway"
  react:
    build:
      context: ./VDPR-React
      dockerfile: ./Dockerfile
    ports:
      - "80:3000"
  redis:
    image: "redis:alpine"
